name: jwk_plus

version: 1.0.0

homepage: https://github.com/emz-hanauer/dart-cryptography

description: JWK (JSON Web Key) encoding and decoding (for package:cryptography).

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.17.0
  cryptography_plus: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
