name: cryptography_flutter_plus

version: 3.0.0

homepage: https://github.com/emz-hanauer/dart-cryptography

description:
  Makes 'package:cryptography_plus' use platform APIs in Android, iOS, and Mac OS X. The package can
  make performance up to 100 times better.

topics:
  - crypto

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

# Open-source contributors:
#
# If you add a dependency to the package, please help
# readers of pubspec.yaml to understand who maintains it
# and any other useful information about it.
dependencies:
  #
  # Packages by github.com/dint-dev:
  #
  cryptography_plus: ^3.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.dint.cryptography_flutter
        pluginClass: CryptographyFlutterPlugin
        dartPluginClass: FlutterCryptography
      ios:
        pluginClass: CryptographyFlutterPlugin
        dartPluginClass: FlutterCryptography
      linux:
        dartPluginClass: FlutterCryptography
      macos:
        pluginClass: CryptographyFlutterPlugin
        dartPluginClass: FlutterCryptography
      windows:
        dartPluginClass: FlutterCryptography
