name: cryptography_test

version: 1.0.0

homepage: https://github.com/emz-hanauer/dart-cryptography

description:
  A package for testing and benchmarking cryptographic algorithm implementations that
  implement "package:cryptography" interfaces.

resolution: workspace

environment:
  sdk: ^3.5.0

# Open-source contributors:
#
# If you add a dependency to the package, please help
# readers of pubspec.yaml to understand who maintains it
# and any other useful information about it.
dependencies:
  #
  # Packages by Google:
  #
  collection: ^1.17.0
  crypto: ^3.0.3
  test: ^1.24.0
  typed_data: ^1.3.0

  #
  # Packages by github.com/dint-dev:
  #
  cryptography_plus: ^3.0.0

dev_dependencies:
  #
  # Packages by Google:
  #
  lints: ^6.0.0
